# Generated by Django 4.2.2 on 2023-06-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=60, null=True, unique=True)),
                ('usertype', models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer')], max_length=10, null=True)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('notsay', 'Prefer Not to say')], max_length=6, null=True)),
                ('activated', models.BooleanField(default=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
